# Generated by Django 3.0.6 on 2020-05-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_auto_20200504_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInput',
            new_name='Contact',
        ),
    ]
