# Generated by Django 3.0.6 on 2020-05-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='text',
        ),
        migrations.AddField(
            model_name='userinput',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='userinput',
            name='number',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
